version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user
      POSTGRES_DB: user
    ports:
      - "5432:5432"
  backend:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/user
    depends_on:
      - db
    ports:
      - "8080:8080"
  frontend:
    image: ghcr.io/bizinmitya/front-react-avito:v1.18
    depends_on:
      - backend
    ports:
      - "3000:3000"