###
#Аноним
###
GET http://localhost:8080/ads
### получать список объявлений
GET http://localhost:8080/ads/1
### получать одно объявление 401
POST http://localhost:8080/ads
Content-Type: application/json

{
  "image": "123",
  "price": 123,
  "description": "123",
  "pk": 1233,
  "title": "123"
}
###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "test@test.tt",
  "password": "password"
}
###
POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "test@test3.tt",
  "password": "password1"
}
###
# User
###
GET http://localhost:8080/ads
Content-Type: application/json
Authorization: Basic test@test.tt password
### получать список объявлений
GET http://localhost:8080/ads/me
Content-Type: application/json
Authorization: Basic test@test.tt password
### получать список своих объявлений
GET http://localhost:8080/ads/1
Content-Type: application/json
Authorization: Basic test@test.tt password
### получать одно объявление
POST http://localhost:8080/ads
Content-Type: multipart/form-data; boundary=boundary
Authorization: Basic test@test.tt password

--boundary
Content-Disposition: form-data; name="properties";
Content-Type: application/json

{
  "image": "https://mykaleidoscope.ru/uploads/posts/2022-06/1656422760_27-mykaleidoscope-ru-p-svetlo-rizhie-volosi-devushka-krasivo-foto-28.jpg",
  "price": 123,
  "description": "123",
  "title": "123"
}
--boundary
Content-Disposition: form-data; name="image"; filename="/home/sl/Изображения/Screenshot_20230625_143523.bmp";

--boundary--
### создавать объявление
POST http://localhost:8080/ads
Content-Type: multipart/form-data; boundary=boundary
Authorization: Basic test@tst.tt password

--boundary
Content-Disposition: form-data; name="properties";
Content-Type: application/json

{
  "price": 123,
  "description": "123",
  "title": "123"
}
--boundary
Content-Disposition: form-data; name="image"; filename="/home/sl/Изображения/Screenshot_20230625_143523.bmp";

--boundary--
### создавать объявление t2
PATCH http://localhost:8080/ads/1
Content-Type: application/json
Authorization: Basic test@tst.tt password

{
  "price": 123,
  "description": "12sd3",
  "title": "12sdf3"
}
### редактировать свое объявление
PATCH http://localhost:8080/ads/2
Content-Type: application/json
Authorization: Basic test@test.tt password

{
  "price": 123,
  "description": "12sd3",
  "title": "12sdf3"
}
### редактировать свое объявление v2 403
PATCH http://localhost:8080/ads/2222
Content-Type: application/json
Authorization: Basic test@test.tt password

{
  "price": 123,
  "description": "12sd3",
  "title": "12sdf3"
}
### редактировать свое объявление v3 404
DELETE http://localhost:8080/ads/1
Authorization: Basic test@test.tt password
### удалять свое объявление
DELETE http://localhost:8080/ads/2
Authorization: Basic test@test.tt password
### удалять свое объявление v2 403
DELETE http://localhost:8080/ads/2222
Authorization: Basic test@test.tt password
### удалять свое объявление v3 404
GET http://localhost:8080/ads/1/comments
Authorization: Basic test@test.tt password
### получать список комментариев
POST http://localhost:8080/ads/1/comments
Authorization: Basic test@test.tt password
Content-Type: application/json

{
  "text": "string"
}
### создавать комментарии
PATCH http://localhost:8080/ads/1/comments/4
Authorization: Basic test@test.tt password
Content-Type: application/json

{
  "text": "strin3g",
  "createdAt": 123123123123
}
### редактировать комментарии
PATCH http://localhost:8080/ads/1/comments/4
Authorization: Basic test@tst.tt password
Content-Type: application/json

{
  "text": "string",
  "createdAt": 123123123123
}
### редактировать комментарии2
DELETE http://localhost:8080/ads/1/comments/3
Authorization: Basic test@test.tt password
### удалять свои комментарии
DELETE http://localhost:8080/ads/1/comments/3
Authorization: Basic test@tst.tt password
### удалять свои комментарии2
###

### ADMIN
###




GET http://localhost:8080/users/me
Content-Type: application/json
Authorization: Basic test@test.tt password

###
PATCH http://localhost:8080/users/me
Content-Type: application/json
Authorization: Basic test@test.tt password

{
  "phone": "33333",
  "lastName": "Ivanov",
  "firstName": "Ivan",
  "email": "test@test.tt",
  "id": 3
}

###
POST http://localhost:8080/users/set_password
Content-Type: application/json
Authorization: Basic test@test.tt password

{
  "newPassword": "password",
  "currentPassword": "password"
}



###
PATCH http://localhost:8080/users/me/image
Content-Type: multipart/form-data; boundary=boundary
Authorization: Basic test@test.tt password

--boundary
Content-Disposition: form-data; name="image"; filename="qwe.bmp";

< /home/sl/qwe.bmp
--boundary--
###
GET http://localhost:8080/users/me
Content-Type: application/json
Authorization: Basic test@test.tt password

###
GET http://localhost:8080/images/5810ea3d-63f6-4b6d-8b5a-e4b9017f9b16

###
POST http://localhost:8080/ads
Content-Type: multipart/form-data; boundary=boundary
Authorization: Basic test@test.tt password

--boundary
Content-Disposition: form-data; name="properties";
Content-Type: application/json

{
  "price": 123,
  "description": "123",
  "title": "123"
}
--boundary
Content-Disposition: form-data; name="image"; filename="test.bmp";

< /home/sl/qwe.bmp
--boundary--
### создавать объявление

PATCH http://localhost:8080/ads/2/image
Content-Type: multipart/form-data; boundary=boundary
Authorization: Basic test@test.tt password

--boundary
Content-Disposition: form-data; name="image"; filename="qwe.bmp";

< /home/sl/qwe.bmp
--boundary--