#server:
#  port: 8080

springdoc:
  api-docs:
    enabled: true
  default-produces-media-type: application/json

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: user
    password: example
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml